import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  content: {
    padding: 20,
    paddingBottom: 120,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 16,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  deliveryNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  carrier: {
    fontSize: 13,
    color: '#64748b',
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  project: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3b82f6',
  },
  date: {
    fontSize: 13,
    color: '#94a3b8',
  },
  formTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 10,
    marginTop: 8,
  },
  label: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
    marginBottom: 6,
    marginTop: 10,
  },
<<<<<<< HEAD
  projectChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginRight: 8,
    marginBottom: 8,
  },
  projectChipOn: {
    borderColor: '#3b82f6',
    backgroundColor: '#eff6ff',
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#475569',
  },
  chipTextOn: {
    color: '#3b82f6',
  },
=======
>>>>>>> main
  uploadBtn: {
    backgroundColor: '#3b82f6',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 20,
  },
  uploadBtnText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  msg: {
    marginTop: 8,
    fontSize: 14,
    color: '#dc2626',
  },
<<<<<<< HEAD
  slipMeta: {
    fontSize: 12,
    color: '#94a3b8',
    marginTop: 6,
=======
  slipMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  slipMeta: {
    fontSize: 12,
    color: '#94a3b8',
    flex: 1,
  },
  deleteSlipText: {
    fontSize: 13,
    color: '#dc2626',
    fontWeight: '700',
  },
  signedBy: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '600',
    marginTop: 4,
  },
  addItemsBtn: {
    marginTop: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: '#e2e8f0',
    alignSelf: 'flex-start',
  },
  addItemsText: {
    color: '#475569',
    fontWeight: '600',
    fontSize: 13,
  },
  lineItemRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-end',
    marginBottom: 8,
  },
  lineItemDesc: {
    flex: 3,
  },
  lineItemQty: {
    flex: 1,
  },
  inputSmall: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 14,
    color: '#0f172a',
    flex: 1,
  },
  removeItemBtn: {
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  removeItemText: {
    color: '#dc2626',
    fontWeight: '700',
    fontSize: 16,
  },
  submitItemsBtn: {
    backgroundColor: '#22c55e',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  submitItemsText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 14,
  },
  existingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 3,
  },
  existingItemDesc: {
    fontSize: 13,
    color: '#334155',
    flex: 1,
  },
  existingItemQty: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '600',
  },
  shortageSection: {
    marginTop: 20,
    marginBottom: 12,
  },
  shortageTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 10,
  },
  shortageRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  shortageDesc: {
    fontSize: 14,
    color: '#334155',
    flex: 1,
  },
  shortageNums: {
    fontSize: 13,
    color: '#64748b',
  },
  shortageAlert: {
    fontSize: 13,
    color: '#dc2626',
    fontWeight: '700',
  },
  shortageOk: {
    fontSize: 13,
    color: '#16a34a',
    fontWeight: '700',
  },
  lineItemBlock: {
    marginBottom: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  itemLocationColumn: {
    marginTop: 10,
    width: '100%',
  },
  itemLocationLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 6,
  },
  pickerShell: {
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 8,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  picker: {
    width: '100%',
  },
  locationInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    color: '#0f172a',
  },
  viewMoreLink: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '700',
    color: '#2563eb',
  },
  shortageRowMain: {
    flex: 1,
    marginRight: 10,
  },
  shortageRowSide: {
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  shortageSummaryLine: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 4,
  },
  detailModalRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  detailModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  detailModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
    flex: 1,
    marginRight: 12,
    flexShrink: 1,
  },
  detailModalClose: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2563eb',
  },
  detailModalScroll: {
    padding: 20,
    paddingBottom: 48,
  },
  detailSectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginTop: 16,
    marginBottom: 6,
  },
  detailSectionHint: {
    fontSize: 12,
    color: '#94a3b8',
    lineHeight: 17,
    marginBottom: 8,
    marginTop: -2,
  },
  detailBody: {
    fontSize: 15,
    color: '#0f172a',
    lineHeight: 22,
  },
  detailMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 8,
  },
  detailMetaItem: {
    fontSize: 14,
    color: '#475569',
  },
  detailMetaStrong: {
    fontWeight: '700',
    color: '#0f172a',
  },
  placementRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  placementLoc: {
    fontSize: 14,
    color: '#334155',
    flex: 1,
    marginRight: 8,
  },
  placementQty: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
  },
  placementQtyLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  detailEmptyPlacements: {
    fontSize: 14,
    color: '#94a3b8',
    fontStyle: 'italic',
  },
  slipDetailLine: {
    marginBottom: 16,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  slipDetailOpenPdf: {
    marginTop: 20,
    backgroundColor: '#eff6ff',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  slipDetailOpenPdfText: {
    color: '#2563eb',
    fontWeight: '700',
    fontSize: 15,
>>>>>>> main
  },
});
